/**
 * Explore DTOs for AI-powered knowledge discovery
 */

import type { MemoListItemDto } from './memo.js';

/**
 * Request to explore/query the knowledge base
 */
export interface ExploreQueryDto {
  /** Query text to explore the knowledge base */
  query: string;
  /** Optional conversation context for follow-up questions */
  context?: string;
}

/**
 * Source memo reference in AI response
 */
export interface ExploreSourceDto {
  /** Memo ID being referenced */
  memoId: string;
  /** Content summary (first 200 chars) */
  content: string;
  /** Relevance score (0-1) */
  relevanceScore: number;
  /** Created timestamp in milliseconds */
  createdAt: number;
}

/**
 * Response from AI exploration
 */
export interface ExploreResponseDto {
  /** AI-generated answer to the query */
  answer: string;
  /** Array of source memo references */
  sources: ExploreSourceDto[];
  /** Related topics discovered */
  relatedTopics?: string[];
  /** Suggested follow-up questions */
  suggestedQuestions?: string[];
}

/**
 * Agent state for LangChain DeepAgents
 * Passed between agents in the chain
 */
export interface AgentState {
  /** Query text */
  query: string;
  /** User ID */
  uid: string;
  /** Optional conversation context */
  context?: string;
  /** Retrieved memos from vector search */
  retrievedMemos?: MemoListItemDto[];
  /** Relevance scores for each memo (memoId -> score) */
  relevanceScores?: Record<string, number>;
  /** Analysis text from relation/attachment agents */
  analysis?: string;
  /** Final answer generated by summary agent */
  answer?: string;
  /** Source memo references */
  sources?: ExploreSourceDto[];
  /** Suggested follow-up questions */
  suggestedQuestions?: string[];
  /** Error message if agent failed */
  error?: string;
}

/**
 * Retrieval Agent output
 */
export interface RetrievalAgentOutput {
  /** Retrieved memos from vector search */
  memos: MemoListItemDto[];
  /** Relevance scores for each memo (memoId -> score) */
  relevanceScores: Record<string, number>;
}

/**
 * Relation Analysis Agent output
 */
export interface RelationAnalysisOutput {
  /** Array of related memo IDs */
  relatedMemoIds: string[];
  /** Relation types for each memo (memoId -> relation types) */
  relationTypes: Record<string, string[]>;
  /** Analysis text describing relationships */
  analysis: string;
}

/**
 * Attachment Analysis Agent output
 */
export interface AttachmentAnalysisOutput {
  /** Attachment summaries (attachmentId -> summary) */
  attachmentSummaries: Record<string, string>;
  /** Key insights extracted from attachments */
  keyInsights: string[];
}

/**
 * Summary Agent output - final response
 */
export interface SummaryAgentOutput {
  /** Final answer to the query */
  answer: string;
  /** Source memo references */
  sources: ExploreSourceDto[];
  /** Related topics discovered */
  relatedTopics?: string[];
  /** Suggested follow-up questions */
  suggestedQuestions?: string[];
}

/**
 * Node in the relationship graph
 */
export interface RelationGraphNodeDto {
  /** Node ID (memo ID) */
  id: string;
  /** Node type in the graph */
  type: 'source' | 'related' | 'backlink';
  /** Memo title or first line */
  title: string;
  /** Memo content summary */
  content: string;
  /** Created timestamp in milliseconds */
  createdAt: number;
}

/**
 * Edge in the relationship graph (connection between nodes)
 */
export interface RelationGraphEdgeDto {
  /** Source node ID */
  source: string;
  /** Target node ID */
  target: string;
  /** Edge type */
  type: 'outgoing' | 'incoming' | 'thematic' | 'temporal' | 'tag';
  /** Optional edge label */
  label?: string;
}

/**
 * Relationship graph data for visualization
 */
export interface RelationGraphDto {
  /** Array of graph nodes */
  nodes: RelationGraphNodeDto[];
  /** Array of graph edges */
  edges: RelationGraphEdgeDto[];
  /** Center memo ID (root of the graph) */
  centerMemoId: string;
  /** Analysis text describing the relationship graph */
  analysis: string;
}

/**
 * Request to explore relationships for a memo
 */
export interface ExploreRelationsDto {
  /** Memo ID to explore relationships for */
  memoId: string;
  /** Whether to include backlinks (memos linking to this memo) */
  includeBacklinks?: boolean;
  /** Maximum depth of relationship traversal */
  maxDepth?: number;
}

/**
 * Response with relationship graph data
 */
export interface ExploreRelationsResponseDto {
  /** Relationship graph data */
  graph: RelationGraphDto;
  /** Suggested explorations based on the graph */
  suggestedExplorations?: string[];
}

// ==================== AI Conversation DTOs ====================

/**
 * AI Message source reference
 * Stores memo references in conversation messages
 */
export interface AIMessageSourceDto {
  /** Memo ID being referenced */
  memoId?: string;
  /** Content summary of the memo */
  content?: string;
  /** Similarity score (deprecated, use relevanceScore) */
  similarity?: number;
  /** Relevance score (0-1) */
  relevanceScore?: number;
  /** Created timestamp in milliseconds */
  createdAt?: number;
}

/**
 * AI Message DTO
 */
export interface AIMessageDto {
  /** Unique message identifier */
  messageId: string;
  /** Conversation ID this message belongs to */
  conversationId: string;
  /** Message role (user or assistant) */
  role: 'user' | 'assistant';
  /** Message content text */
  content: string;
  /** Array of source memo references */
  sources?: AIMessageSourceDto[];
  /** Created timestamp in milliseconds */
  createdAt: number;
}

/**
 * AI Conversation DTO
 */
export interface AIConversationDto {
  /** Unique conversation identifier */
  conversationId: string;
  /** Conversation title */
  title: string;
  /** Created timestamp in milliseconds */
  createdAt: number;
  /** Updated timestamp in milliseconds */
  updatedAt: number;
  /** Number of messages in conversation */
  messageCount?: number;
}

/**
 * AI Conversation with messages DTO
 */
export interface AIConversationDetailDto extends AIConversationDto {
  /** Array of messages in the conversation */
  messages: AIMessageDto[];
}

/**
 * Create conversation request DTO
 */
export interface CreateConversationDto {
  /** Optional conversation title */
  title?: string;
}

/**
 * Update conversation request DTO
 */
export interface UpdateConversationDto {
  /** New conversation title */
  title: string;
}

/**
 * Add message request DTO
 */
export interface AddMessageDto {
  /** Message role (user or assistant) */
  role: 'user' | 'assistant';
  /** Message content text */
  content: string;
  /** Array of source memo references */
  sources?: AIMessageSourceDto[];
}

/**
 * Conversation list response DTO
 */
export interface ConversationListResponseDto {
  /** Array of conversation items */
  items: AIConversationDto[];
  /** Total number of conversations */
  total: number;
}

/**
 * Conversation list query params
 */
export interface ConversationListQueryDto {
  /** Page number for pagination */
  page?: number;
  /** Items per page */
  limit?: number;
}
