export const OBJECT_TYPE = {
  CATEGORY: 'CATEGORY',
  MEMO: 'MEMO',
  PAGE: 'PAGE',
  ANNOTATION: 'ANNOTATION',
  INBOX: 'INBOX',
  FILE: 'FILE',
  SPACE: 'SPACE',
  NOTE: 'NOTE',
  LIBRARY: 'LIBRARY',
  USER: 'USER',
  TIMELINE: 'TIMELINE',
  RELATION: 'RELATION',
  CONVERSATION: 'CONVERSATION',
  MESSAGE: 'MESSAGE',
  RECOMMENDATION: 'RECOMMENDATION',
};

export const PAGE_CATEGORY = {
  NOTE: 'NOTE',
  DAILY: 'DAILY',
};
